apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: petclinic
  namespace: apps
spec:
  build:
    resources: {}
  builder:
    kind: ClusterBuilder
    name: default
  cacheSize: 2G
  failedBuildHistoryLimit: 10
  imageTaggingStrategy: BuildNumber
  serviceAccount: default
  source:
    git:
      revision: master
      url: http://gitea.apps.kubeages.com/ages/spring-petclinic-data-jdbc
  successBuildHistoryLimit: 10
  tag: harbor.apps.kubeages.com/ages/spring-petclinic-jdbc-mysql