apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: petclinic
  namespace: apps
spec:
  build:
    resources: {}
    env:
    - name: BP_MAVEN_BUILD_ARGUMENTS
      value: "package -Dmaven.test.skip=true"
  builder:
    kind: ClusterBuilder
    name: default
  cacheSize: 2G
  failedBuildHistoryLimit: 10
  imageTaggingStrategy: BuildNumber
  serviceAccount: default
  source:
    git:
      revision: main
      url: https://github.com/kubeages/spring-petclinic-data-jdbc.git
  successBuildHistoryLimit: 10
  tag: registry.cloud-garage.net/ages/spring-petclinic-jdbc-mysql