apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-petclinic-jdbc-mysql
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-petclinic-jdbc-mysql
    apps.tanzu.vmware.com/has-tests: false
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/metric: "rps"
      autoscaling.knative.dev/target: "10"
      autoscaling.knative.dev/window: "10s"
      autoscaling.knative.dev/max-scale: "5"
      autoscaling.knative.dev/min-scale: "1"
  build:
    resources: {}
    env:
    - name: BP_MAVEN_BUILD_ARGUMENTS
      value: "package -Dmaven.test.skip=true"
  source:
    git:
      ref:
        branch: main
      url: https://github.com/kubeages/spring-petclinic-data-jdbc.git